ORG_EMAIL = "@copiacs.com" 
FROM_EMAIL = "pankaj.u" + ORG_EMAIL 
FROM_PWD = "copia@123" 
SMTP_SERVER = "imap.gmail.com"
SMTP_PORT = 993
SENDER_EMAIL_ID = "pankajunhale@gmail.com"
STREAM_TYPE_OCTET = "application/octet-stream"
SENT_SINCE_QUERY = 'SENTSINCE'
CUSTOMER_PURCHASE_ORDER_TEMPLATE = 'assets/resources/'
CUSTOMER_PURCHASE_ORDERS = 'assets/resources/purchase-orders/'